apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: modresorts
  namespace: NAMESPACE
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server Liberty Core
    productEntitlementSource: IBM Cloud Pak for Applications
  applicationVersion: v2
  topologySpreadConstraints:
    constraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: zone
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
  serviceAccount:
    mountToken: true
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 60
  applicationImage: IMAGE_REFERENCE
  expose: true
  manageTLS: true
  replicas: 1
  pullPolicy: Always
  manageLTPA: false
